name: rl1
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.6
    - scikit-learn==0.19.1
    - cython
    - openblas
    - numpy
    - matplotlib
    - bokeh
    - pillow
    - scikit-image
    - scipy
    - h5py
    - flask-socketio
    - seaborn
    - pandas
    - ffmpeg
    - imageio
    - nltk
    - gensim
    - pip:
        - jupyter
        - moviepy
        - tensorflow==1.8.0
        - keras
        - pydot
        - nltk
        - pandas-gbq
        - awscli
        - google-cloud
        - pyvirtualdisplay
        - gym
        - gym-retro
